# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCAP5QuDcx0cAIrOeh8hImXG71kShbsO
"""

import streamlit as st
import PyPDF2
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from openai import OpenAI

# ------------------------------
# PAGE CONFIG
# ------------------------------
st.set_page_config(page_title="GenAI Resume Matcher", layout="wide")
st.title("📄 GenAI Resume–Job Matcher (Mini ATS)")

# ------------------------------
# LOAD OPENAI CLIENT FROM SECRETS
# ------------------------------
try:
    client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])
except Exception:
    st.error("OpenAI API Key not found. Please add it in Streamlit Secrets.")
    st.stop()

# ------------------------------
# LOAD EMBEDDING MODEL (cached)
# ------------------------------
@st.cache_resource
def load_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

embedder = load_model()

# ------------------------------
# PDF TEXT EXTRACTION
# ------------------------------
def extract_text_from_pdf(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"
    return text

def read_file(file):
    if file.name.endswith(".pdf"):
        return extract_text_from_pdf(file)
    else:
        return file.read().decode("utf-8", errors="ignore")

def clean_text(text):
    text = text.lower()
    text = " ".join(text.split())
    return text

# ------------------------------
# SIMILARITY COMPUTATION
# ------------------------------
def compute_similarity(jd_text, resumes_texts):
    jd_emb = embedder.encode([jd_text])
    resume_embs = embedder.encode(resumes_texts)
    sims = cosine_similarity(jd_emb, resume_embs)[0]
    return sims

# ------------------------------
# VERDICT LOGIC
# ------------------------------
def verdict_from_score(score_percent):
    if score_percent >= 70:
        return "Shortlist"
    elif score_percent >= 50:
        return "Maybe"
    else:
        return "Reject"

# ------------------------------
# LLM EXPLANATION
# ------------------------------
def generate_explanation(jd_text, resume_text, score_percent):
    prompt = f"""
    Job Description:
    {jd_text}

    Resume:
    {resume_text}

    Match Score: {score_percent}%

    Task:
    Explain why this candidate received this score.
    Provide:
    1. Key strengths matching the job
    2. Missing or weak skills
    3. Final recommendation aligned with the score (Shortlist/Maybe/Reject)
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3
    )

    return response.choices[0].message.content

# ------------------------------
# FILE UPLOAD UI
# ------------------------------
st.header("📂 Upload Files")

jd_file = st.file_uploader("Upload Job Description (TXT or PDF)", type=["txt", "pdf"])
resume_files = st.file_uploader(
    "Upload Multiple Resumes (PDF or TXT)",
    type=["pdf", "txt"],
    accept_multiple_files=True
)

# ------------------------------
# RUN MATCHING
# ------------------------------
if st.button("🚀 Run Resume Matching"):

    if not jd_file or not resume_files:
        st.error("Please upload both a Job Description and at least one resume.")
        st.stop()

    with st.spinner("Processing resumes..."):

        jd_text = clean_text(read_file(jd_file))

        resumes_texts = []
        resume_names = []

        for file in resume_files:
            text = clean_text(read_file(file))
            resumes_texts.append(text)
            resume_names.append(file.name)

        sims = compute_similarity(jd_text, resumes_texts)

        results = []
        for name, sim, resume_text in zip(resume_names, sims, resumes_texts):
            score_percent = round(float(sim) * 100, 2)
            verdict = verdict_from_score(score_percent)
            explanation = generate_explanation(jd_text, resume_text, score_percent)

            results.append((name, score_percent, verdict, explanation))

        results.sort(key=lambda x: x[1], reverse=True)

    st.success("✅ Matching Complete!")

    st.header("📊 Candidate Ranking")

    for i, (name, score, verdict, exp) in enumerate(results, 1):
        with st.expander(f"Rank {i}: {name} | Match: {score}% | Verdict: {verdict}"):
            st.write(f"**Match Score:** {score}%")
            st.write(f"**Verdict:** {verdict}")
            st.markdown("---")
            st.write(exp)

